[package]
name = "boxrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
glium = "0.32.1"
image = "0.24.6"
pretty_assertions = "1.3.0"