name: Main branch tests

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add formatter
        run: rustup component add rustfmt
      - name: Formatting
        run: cargo fmt --all --check
      - name: Add clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          path: main
      - name: Run coverage.sh
        run: |
          cd main
          ./coverage.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: main/target/debug/coverage/
      - name: Check out artifacts branch
        uses: actions/checkout@v3
        with:
          ref: artifacts
          path: artifacts
          token: ${{ secrets.ARTIFACTS_PAT }}
      - name: Publish code coverage results
        run: |
          cd artifacts
          ../main/.github/publish-coverage.sh