name: Run cargo test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-coverage:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Cinstrument-coverage"
      CARGO_INCREMENTAL: "0"
      LLVM_PROFILE_FILE: "your_name-%p-%m.profraw"
    steps:
      - uses: actions/checkout@v3
      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview
      - name: Install grcov
        run: cargo install grcov
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Generate coverage report
        run: grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./target/debug/coverage/